name: azdocli
base: core22
version: git
summary: CLI tool for interacting with Azure DevOps
description: |
  A powerful command-line interface for Azure DevOps that provides repository 
  management, pipeline management, and board management capabilities.
  
  Features include:
  - Repository management (list, create, delete, clone, view, and manage pull requests)
  - Pipeline management
  - Board management  
  - Authentication using Personal Access Tokens (PAT)
  - Default project support

grade: stable
confinement: strict

apps:
  azdocli:
    command: bin/azdocli
    aliases: [ado, azdo, adocli]

parts:
  azdocli:
    plugin: rust
    source: .
    build-packages:
      - libssl-dev
      - pkg-config
