//! Reading and writing the comment threads on a pull request.

use super::PrContext;
use anyhow::Result;
use azure_devops_rust_api::git::models::{comment, comment_thread, GitPullRequestCommentThread};
use colored::Colorize;

/// Renders a thread status as the label the web UI uses.
pub(super) fn thread_status_label(status: Option<&comment_thread::Status>) -> &'static str {
    match status {
        Some(comment_thread::Status::Active) => "active",
        Some(comment_thread::Status::Fixed) => "fixed",
        Some(comment_thread::Status::WontFix) => "won't fix",
        Some(comment_thread::Status::Closed) => "closed",
        Some(comment_thread::Status::ByDesign) => "by design",
        Some(comment_thread::Status::Pending) => "pending",
        _ => "unknown",
    }
}

/// Reports whether a thread was generated by Azure DevOps rather than a person.
///
/// System threads record events such as pushes and vote changes; they are noise
/// when reading a discussion, so they are hidden unless explicitly requested.
pub(super) fn is_system_thread(thread: &GitPullRequestCommentThread) -> bool {
    let comments = &thread.comment_thread.comments;

    !comments.is_empty()
        && comments.iter().all(|entry| {
            matches!(
                entry.comment_type,
                Some(comment::CommentType::System) | Some(comment::CommentType::Unknown)
            )
        })
}

/// Selects the threads worth showing for the requested verbosity.
pub(super) fn visible_threads(
    threads: &[GitPullRequestCommentThread],
    show_all: bool,
) -> Vec<&GitPullRequestCommentThread> {
    threads
        .iter()
        .filter(|thread| {
            show_all
                || (!is_system_thread(thread) && !thread.comment_thread.is_deleted.unwrap_or(false))
        })
        .collect()
}

/// Describes the file and line a thread is anchored to, if any.
pub(super) fn thread_location(thread: &GitPullRequestCommentThread) -> Option<String> {
    let context = thread.comment_thread.thread_context.as_ref()?;
    let file_path = context.file_path.as_deref()?;

    let line = context
        .right_file_start
        .as_ref()
        .or(context.left_file_start.as_ref())
        .and_then(|position| position.line);

    Some(match line {
        Some(line) => format!("{file_path}:{line}"),
        None => file_path.to_string(),
    })
}

/// Lists the comment threads on a pull request.
pub(super) async fn list_threads(
    project: Option<&str>,
    repo: &str,
    id: &str,
    show_all: bool,
) -> Result<()> {
    let ctx = PrContext::new(project, repo, id).await?;

    let threads = ctx
        .client
        .pull_request_threads_client()
        .list(
            &ctx.creds.organization,
            &ctx.repository_id,
            ctx.pull_request_id,
            &ctx.project,
        )
        .await?
        .value;

    display_threads(&visible_threads(&threads, show_all));
    Ok(())
}

/// Prints each thread with its status, anchor and comments.
fn display_threads(threads: &[&GitPullRequestCommentThread]) {
    if threads.is_empty() {
        println!("No comment threads found.");
        return;
    }

    println!("📋 Comment Threads");
    println!("==================");

    for thread in threads {
        let thread_id = thread
            .comment_thread
            .id
            .map(|id| id.to_string())
            .unwrap_or_else(|| "-".to_string());

        println!();
        println!(
            "Thread {} [{}]",
            thread_id.bold(),
            thread_status_label(thread.comment_thread.status.as_ref())
        );

        if let Some(location) = thread_location(thread) {
            println!("  📄 {location}");
        }

        for entry in &thread.comment_thread.comments {
            let author = entry
                .author
                .as_ref()
                .and_then(|author| author.graph_subject_base.display_name.as_deref())
                .unwrap_or("Unknown");

            println!(
                "  • {}: {}",
                author.bold(),
                entry.content.as_deref().unwrap_or("")
            );
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use azure_devops_rust_api::git::models::{Comment, CommentPosition, CommentThreadContext};

    fn thread(comment_type: Option<comment::CommentType>) -> GitPullRequestCommentThread {
        let mut entry = Comment::new();
        entry.content = Some("hello".to_string());
        entry.comment_type = comment_type;

        let mut thread = GitPullRequestCommentThread::new();
        thread.comment_thread.id = Some(1);
        thread.comment_thread.comments = vec![entry];
        thread
    }

    #[test]
    fn status_labels_match_the_web_ui() {
        assert_eq!(
            thread_status_label(Some(&comment_thread::Status::WontFix)),
            "won't fix"
        );
        assert_eq!(thread_status_label(None), "unknown");
    }

    #[test]
    fn system_threads_are_detected() {
        assert!(is_system_thread(&thread(Some(
            comment::CommentType::System
        ))));
        assert!(!is_system_thread(&thread(Some(comment::CommentType::Text))));
    }

    #[test]
    fn empty_threads_are_not_treated_as_system_threads() {
        let mut empty = GitPullRequestCommentThread::new();
        empty.comment_thread.comments = Vec::new();

        assert!(!is_system_thread(&empty));
    }

    #[test]
    fn visible_threads_hides_system_and_deleted_threads_by_default() {
        let mut deleted = thread(Some(comment::CommentType::Text));
        deleted.comment_thread.is_deleted = Some(true);

        let threads = vec![
            thread(Some(comment::CommentType::Text)),
            thread(Some(comment::CommentType::System)),
            deleted,
        ];

        assert_eq!(visible_threads(&threads, false).len(), 1);
        assert_eq!(visible_threads(&threads, true).len(), 3);
    }

    #[test]
    fn thread_location_reports_file_and_line() {
        let mut with_context = thread(Some(comment::CommentType::Text));
        let mut context = CommentThreadContext::new();
        context.file_path = Some("/src/main.rs".to_string());
        let mut position = CommentPosition::new();
        position.line = Some(12);
        context.right_file_start = Some(position);
        with_context.comment_thread.thread_context = Some(context);

        assert_eq!(
            thread_location(&with_context),
            Some("/src/main.rs:12".to_string())
        );
    }

    #[test]
    fn thread_location_is_none_without_a_file() {
        assert_eq!(
            thread_location(&thread(Some(comment::CommentType::Text))),
            None
        );
    }
}
