name: azdocli
base: core22
version: git
summary: CLI tool for interacting with Azure DevOps
description: |
  Azure DevOps CLI is a command-line tool that provides seamless interaction 
  with Azure DevOps services. Built with Rust for performance and reliability, 
  it offers comprehensive features for managing repositories, pipelines, boards, 
  and more.

  Features:
  - Repository Management: List, create, delete, clone, view, and manage pull requests
  - Pipeline Management: Manage Azure DevOps pipelines  
  - Board Management: Manage Azure DevOps boards
  - Authentication: Secure login using Personal Access Tokens (PAT)
  - Default Project: Set a default project to avoid specifying --project for every command

grade: stable
confinement: strict

apps:
  ado:
    command: ado
    plugs:
      - home
      - network
      - network-bind

parts:
  azdocli:
    plugin: dump
    source: artifacts/
    organize:
      ado: bin/ado
    stage:
      - bin/ado