name: Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - os: windows-latest
            target: x86_64-windows
          - os: windows-11-arm
            target: arm64-windows
          - os: ubuntu-latest
            target: x64-linux
          - os: ubuntu-24.04-arm
            target: arm64-linux
          - os: macos-latest
            target: arm64-apple-darwin
          - os: macos-13
            target: x64-apple-darwin

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Rust cache
      uses: Swatinem/rust-cache@v2
      
    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: azdocli-${{ matrix.target }}
        path: target/debug/ado*
        if-no-files-found: error
