name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build:
    name: Build Release
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target: x64-pc-windows-msvc
            artifact_name: ado.exe
            asset_name: azdocli-windows-x86_64.exe
          - os: windows-11-arm
            target: arm64-pc-windows-msvc
            artifact_name: ado.exe
            asset_name: azdocli-windows-arm64.exe
          - os: ubuntu-latest
            target: x64-linux-gnu
            artifact_name: ado
            asset_name: azdocli-linux-x86_64
          - os: ubuntu-24.04-arm
            target: x64-linux-gnu
            artifact_name: ado
            asset_name: azdocli-linux-arm64
          - os: macos-latest
            target: arm64-apple-darwin
            artifact_name: ado
            asset_name: azdocli-macos-x86_64
          - os: macos-13
            target: x64-apple-darwin
            artifact_name: ado
            asset_name: azdocli-macos-x86_64

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Rust cache
      uses: Swatinem/rust-cache@v2
      
    - name: Build
      run: cargo build --release --target ${{ matrix.target }}

    - name: Run tests
      run: cargo test --release --target ${{ matrix.target }}
      
    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: target/${{ matrix.target }}/release/${{ matrix.artifact_name }}
        name: azdocli ${{ github.ref_name }}
        draft: false
        prerelease: false
