name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build Release
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: ado.exe
            asset_name: azdocli-windows-x86_64.exe
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            artifact_name: ado.exe
            asset_name: azdocli-windows-arm64.exe
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: ado
            asset_name: azdocli-linux-x86_64
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            artifact_name: ado
            asset_name: azdocli-linux-arm64
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: ado
            asset_name: azdocli-macos-arm64
          - os: macos-13
            target: x86_64-apple-darwin
            artifact_name: ado
            asset_name: azdocli-macos-x86_64

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Install cross-compilation dependencies
      if: matrix.target == 'aarch64-unknown-linux-gnu'
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu

    - name: Rust cache
      uses: Swatinem/rust-cache@v2
      
    - name: Build
      run: cargo build --release --target ${{ matrix.target }}
      env:
        CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc

    - name: Run tests
      if: matrix.target != 'aarch64-unknown-linux-gnu' && matrix.target != 'aarch64-pc-windows-msvc'
      run: cargo test --release --target ${{ matrix.target }}
      
    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: target/${{ matrix.target }}/release/${{ matrix.artifact_name }}
        name: azdocli ${{ github.ref_name }}
        draft: false
        prerelease: false
